/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class help extends javax.swing.JInternalFrame {

    /**
     * Creates new form help
     */
    public help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1336, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText(" HELP & CONTACT INFORMATION");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 255), new java.awt.Color(153, 0, 153)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 640, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("General Information");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 274, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel3.setText("Baggage");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 140, 280, 27);

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel4.setText("Checked baggage,carry-On baggage,excess,special");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 160, 430, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel5.setText("Transport of Animals");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 240, 340, 26);

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel6.setText("Permitted Animal species only (eg. Pet animals )...");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 270, 490, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel7.setText("Passengers with health restrictions");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 340, 370, 37);

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel8.setText("Special Services  will be provided...");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 370, 380, 35);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel9.setText("Check-in");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 440, 350, 34);

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel10.setText("Online check-in and other check-in options...");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(140, 470, 520, 33);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel11.setText("Upgrade Options");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(140, 530, 310, 34);

        jLabel12.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel12.setText("Upgrade to Premium Economy, Business or First Class..");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(140, 570, 490, 29);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel13.setText("Rebooking ,Cancellation and refunds");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(820, 10, 390, 27);

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel14.setText("Services for your booking,including in the event ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(820, 40, 460, 27);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel15.setText("Invoices and Receipt");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(820, 130, 350, 30);

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel16.setText("Download or request receipt");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(820, 160, 420, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel17.setText("Children and Families");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(820, 210, 330, 30);

        jLabel18.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel18.setText("Special care and service will be provided..");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(820, 240, 420, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel19.setText("Advance Seat reservation and seat maps..");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(810, 300, 450, 30);

        jLabel20.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel20.setText("seat choice before check-in..");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(820, 330, 320, 30);

        jLabel21.setFont(new java.awt.Font("Algerian", 1, 28)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 153));
        jLabel21.setText(" Contact   Us   :  TOLL FREE");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(810, 390, 430, 40);

        jLabel22.setFont(new java.awt.Font("SimSun-ExtB", 1, 20)); // NOI18N
        jLabel22.setText("For More Queries Feel Free To Contact Our Group.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(760, 430, 540, 30);

        jLabel23.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 102));
        jLabel23.setText("+91 9167003333");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(970, 470, 230, 30);

        jLabel24.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel24.setText("Monday To Saturday");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(1050, 500, 240, 30);

        jLabel25.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel25.setText("Timings:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(930, 500, 110, 30);

        jLabel26.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel26.setText("9:00 Am To 11:30 PM");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(970, 540, 310, 40);

        jLabel27.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel27.setText(" of flight disruptions..");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(810, 70, 220, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon("F:\\yypupl.jpeg.jpg")); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(20, 120, 100, 100);

        jLabel29.setIcon(new javax.swing.ImageIcon("F:\\pets.jpg")); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(20, 240, 100, 100);

        jLabel30.setIcon(new javax.swing.ImageIcon("F:\\han.jpg")); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(20, 350, 100, 90);

        jLabel31.setIcon(new javax.swing.ImageIcon("F:\\7.jpg")); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(20, 450, 100, 70);

        jLabel32.setIcon(new javax.swing.ImageIcon("F:\\seatsss.jpg")); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(20, 530, 100, 100);

        jLabel33.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        jLabel33.setText(" and sports baggage.");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(140, 200, 220, 30);

        jLabel34.setIcon(new javax.swing.ImageIcon("F:\\cancelllllllll.jpg")); // NOI18N
        jPanel1.add(jLabel34);
        jLabel34.setBounds(690, 10, 100, 100);

        jLabel35.setIcon(new javax.swing.ImageIcon("F:\\0111111.jpg")); // NOI18N
        jPanel1.add(jLabel35);
        jLabel35.setBounds(690, 120, 100, 80);

        jLabel36.setIcon(new javax.swing.ImageIcon("F:\\bab.jpg")); // NOI18N
        jPanel1.add(jLabel36);
        jLabel36.setBounds(690, 210, 100, 80);

        jLabel37.setIcon(new javax.swing.ImageIcon("F:\\aaa.jpg")); // NOI18N
        jPanel1.add(jLabel37);
        jLabel37.setBounds(690, 300, 100, 80);

        jLabel38.setIcon(new javax.swing.ImageIcon("F:\\;;.jpg")); // NOI18N
        jPanel1.add(jLabel38);
        jLabel38.setBounds(660, 470, 240, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
