
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
    }
       
    Connection con;
    PreparedStatement pst;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        txtpasswd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtut = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " USER LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 30), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1336, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel1.setText("Email Address");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 30, 230, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 100, 200, 50);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.setPreferredSize(new java.awt.Dimension(177, 49));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 440, 220, 80);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(890, 440, 210, 80);

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(690, 30, 380, 50);

        txtpasswd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtpasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswdActionPerformed(evt);
            }
        });
        jPanel1.add(txtpasswd);
        txtpasswd.setBounds(690, 100, 380, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" USER LOGIN ");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 204), new java.awt.Color(255, 255, 255), null, new java.awt.Color(0, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 51))));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 20, 260, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\000.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 100, 90);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel6.setText("User Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(430, 170, 190, 50);

        txtut.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Passenger", "Receptionalist" }));
        jPanel1.add(txtut);
        txtut.setBounds(690, 170, 240, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\login.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1330, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String emailid = txtemail.getText();
        String password = txtpasswd.getText();
                String usertype = txtut.getSelectedItem().toString();


        if(emailid.isEmpty() || password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Invalid Email Id or Password !!!!");
        }
        else
        {
           
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
                
                 pst = con.prepareStatement("select * from user where email=? and password = ? and usertype=? ");
                 pst.setString(1,emailid);
                 pst.setString(2,password);
                  pst.setString(3,usertype);

                ResultSet rs; 
                 rs= pst.executeQuery();
                 if(rs.next())
                 {
                     
                     
                   JOptionPane.showMessageDialog(this, "Login Successfull!!!");

                     Home h = new Home();
                     this.hide();
                     h.setVisible(true);
                     
                     String id  = rs.getString("id");
                     new Home(id,emailid,usertype).setVisible(true);

                     
                 }
                 
                 
                 else 
                 {
                     JOptionPane.showMessageDialog(this,"Invalid Username or Password !!!!!");
                     
                     txtemail.setText("");
                     txtpasswd.setText("");
                    txtut.setSelectedIndex(0);

                     //txtemail.requestFocus();
                 }
                 
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Loginform.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Loginform.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
            
            
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswdActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpasswd;
    private javax.swing.JComboBox<String> txtut;
    // End of variables declaration//GEN-END:variables

}
