
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import java.util.regex.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class payment extends javax.swing.JInternalFrame {

    /**
     * Creates new form payment
     */
   
     public payment() {
        initComponents();
        autoID();
    }
    
    
    
    
    
    
    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        uid = new javax.swing.JTextField();
        fr = new javax.swing.JTextField();
        txtpnr = new javax.swing.JLabel();
        ct = new javax.swing.JComboBox<>();
        cn = new javax.swing.JTextField();
        namcrd = new javax.swing.JTextField();
        exdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        cardno = new javax.swing.JLabel();
        flfr = new javax.swing.JLabel();
        cv = new javax.swing.JLabel();
        noc = new javax.swing.JLabel();
        ccvv = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1336, 768));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 255), new java.awt.Color(102, 0, 102)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1336, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setText("PNR Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(86, 13, 186, 49);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setText("Customer ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(86, 68, 186, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setText("Flight Fair");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(86, 168, 186, 48);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setText("Card Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(86, 227, 186, 38);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setText("Card Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(86, 276, 186, 42);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setText("Name On Card");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(86, 327, 186, 42);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel9.setText("Expiry Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(86, 375, 186, 42);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel10.setText("CVV Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(86, 423, 186, 42);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(107, 500, 194, 66);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setText("ABORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 500, 154, 66);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(651, 500, 159, 66);

        uid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        jPanel1.add(uid);
        uid.setBounds(342, 68, 274, 40);

        fr.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frActionPerformed(evt);
            }
        });
        fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                frKeyReleased(evt);
            }
        });
        jPanel1.add(fr);
        fr.setBounds(342, 168, 274, 48);

        txtpnr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(txtpnr);
        txtpnr.setBounds(342, 13, 274, 49);

        ct.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        ct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit Card", "Credit Card", " " }));
        jPanel1.add(ct);
        ct.setBounds(342, 271, 274, 50);

        cn.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
        });
        jPanel1.add(cn);
        cn.setBounds(342, 222, 274, 43);

        namcrd.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        namcrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namcrdActionPerformed(evt);
            }
        });
        namcrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namcrdKeyReleased(evt);
            }
        });
        jPanel1.add(namcrd);
        namcrd.setBounds(342, 327, 274, 42);

        exdt.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(exdt);
        exdt.setBounds(342, 375, 274, 42);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setText("Flight ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(86, 114, 186, 48);

        fid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });
        jPanel1.add(fid);
        fid.setBounds(344, 120, 270, 40);

        cardno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cardno.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(cardno);
        cardno.setBounds(651, 227, 490, 38);

        flfr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        flfr.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(flfr);
        flfr.setBounds(651, 168, 490, 50);

        cv.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cv.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(cv);
        cv.setBounds(664, 423, 434, 42);

        noc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        noc.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(noc);
        noc.setBounds(664, 327, 434, 42);

        ccvv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ccvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccvvActionPerformed(evt);
            }
        });
        ccvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ccvvKeyReleased(evt);
            }
        });
        jPanel1.add(ccvv);
        ccvv.setBounds(342, 425, 274, 42);

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\pay.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 1180, 610);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("  PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String pnrno = txtpnr.getText();
String custmid = uid.getText();
String flightid = fid.getText();
String fair = fr.getText();
String cardnum = cn.getText();
String cardtype = ct.getSelectedItem().toString();
//DateFormat da= new SimpleDateFormat("yyyy-MM-dd");
//String date= da.format(txtdate.getDate());
//see this;;
String namcard= namcrd.getText();

String exdate= exdt.getText();
String cardcvv= ccvv.getText();





        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
              pst = con.prepareStatement("insert into payment(pnr,custid,flid,fair,cardno,cardtype,nameoncrd,expdate,cvv)values(?,?,?,?,?,?,?,?,?)");
              pst.setString(1,pnrno);
              pst.setString(2,custmid);
              pst.setString(3,flightid);
               pst.setString(4,fair);

              pst.setString(5,cardnum);
              
              pst.setString(6,cardtype);
              
              pst.setString(7,namcard);
              
              pst.setString(8,exdate);
              
              pst.setString(9,cardcvv);
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"Congratulations Payment Done Successfully!!!");
              
              txtpnr.setText("");
              uid.setText("");
                fid.setText("");

              fr.setText("");
               cn.setText("");
               
              ct.setSelectedIndex(0);
             
               namcrd.setText("");
               exdt.setText("");
               
               
               ccvv.setText("");
       
             
              tickets t = new tickets();
        JDesktopPane dp =getDesktopPane();    //very nice!!! Happy
         dp.add(t);
       t.show();
       
             
             
             
        }
        
            
            
            
         catch (ClassNotFoundException ex) {
            Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
        }
              catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }


        
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    
    
   
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

 
    
    
    
    
     public void autoID()
    {
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            java.sql.Statement s = con.createStatement();
             ResultSet rs = s.executeQuery("select MAX(pnr) from payment");
             rs.next();
             rs.getString("MAX(pnr)");
             if(rs.getString("MAX(pnr)") == null)
             {
              txtpnr.setText("PN0001");
                 
             }
             
             else 
             {
               long pnr = Long.parseLong(rs.getString("MAX(pnr)").substring(2,rs.getString("MAX(pnr)").length()));
               pnr++;
               txtpnr.setText("PN" + String.format("%03d", pnr));
             }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnActionPerformed

    private void namcrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namcrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namcrdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frActionPerformed

    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased
        // TODO add your handling code here:
        
        
          String PATTERN ="^[0-9]{0,10}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(cn.getText());
        if(!match.matches())
        {
            cardno.setText("Card Number Is Incorrect !! Plz check the Number!!");
            
        }
        else 
        {
                        cardno.setText(null);

        }
        
        
        
    }//GEN-LAST:event_cnKeyReleased

    private void frKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frKeyReleased
        // TODO add your handling code here:
        
        String PATTERN ="^[0-9]{0,6}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(fr.getText());
        if(!match.matches())
        {
            flfr.setText("Use Decimal values for flight fair!!");
            
        }
        else 
        {
                        flfr.setText(null);

        }
        
        
                 

    }//GEN-LAST:event_frKeyReleased

    private void namcrdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namcrdKeyReleased
        // TODO add your handling code here:
         String PATTERN ="^[A-Za-z]{0,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(namcrd.getText());
        if(!match.matches())
        {
          noc.setText("Naming Is Incorrect !! Plz use only alphabets !!");
            
        }
        else 
        {
                        noc.setText(null);

        }
        
    }//GEN-LAST:event_namcrdKeyReleased

    private void ccvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccvvActionPerformed

    private void ccvvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccvvKeyReleased
        // TODO add your handling code here:
        
        
         String PATTERN ="^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(ccvv.getText());
        if(!match.matches())
        {
            cv.setText("CVV Is Incorrect !! Plz check!!");

        }
        else
        {
            cv.setText(null);

        }

    }//GEN-LAST:event_ccvvKeyReleased

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardno;
    private javax.swing.JPasswordField ccvv;
    private javax.swing.JTextField cn;
    private javax.swing.JComboBox<String> ct;
    private javax.swing.JLabel cv;
    private javax.swing.JTextField exdt;
    private javax.swing.JTextField fid;
    private javax.swing.JLabel flfr;
    private javax.swing.JTextField fr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namcrd;
    private javax.swing.JLabel noc;
    private javax.swing.JLabel txtpnr;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
