


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.sql.ResultSet;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class searchflight extends javax.swing.JInternalFrame {

    /**
     * Creates new form addflight
     */
    public searchflight() {
        initComponents();
 
        
    }
    
    Connection con;
     PreparedStatement pst;

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        dateChooserPanel2 = new datechooser.beans.DateChooserPanel();
        txtdat = new datechooser.beans.DateChooserPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtflight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        txtarr = new javax.swing.JTextField();
        txtfchrg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtfid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtsrc = new javax.swing.JComboBox<>();
        txtdst = new javax.swing.JComboBox<>();
        txtdate = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(648, 666));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel1.setText(" Flight ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 200, 43);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel3.setText("Flight Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 95, 190, 36);

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel4.setText("Source");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 161, 178, 31);

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel5.setText("Destination");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 219, 190, 40);

        txtflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflightActionPerformed(evt);
            }
        });
        jPanel1.add(txtflight);
        txtflight.setBounds(289, 94, 219, 37);

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 286, 190, 40);

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel7.setText("DepatureTime");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 353, 178, 37);

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel8.setText("Arrival Time");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 415, 178, 37);

        jLabel9.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel9.setText("Flight Charge");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 477, 200, 37);

        txtdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeptActionPerformed(evt);
            }
        });
        jPanel1.add(txtdept);
        txtdept.setBounds(289, 353, 219, 37);

        txtarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtarrActionPerformed(evt);
            }
        });
        jPanel1.add(txtarr);
        txtarr.setBounds(289, 415, 219, 37);

        txtfchrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfchrgActionPerformed(evt);
            }
        });
        jPanel1.add(txtfchrg);
        txtfchrg.setBounds(289, 477, 219, 37);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(91, 554, 167, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(605, 555, 153, 49);

        txtfid.setFont(new java.awt.Font("Segoe UI Symbol", 1, 20)); // NOI18N
        jPanel1.add(txtfid);
        txtfid.setBounds(289, 26, 134, 43);

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(488, 26, 155, 43);

        txtsrc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtsrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesh", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia", " " }));
        jPanel1.add(txtsrc);
        txtsrc.setBounds(289, 156, 219, 38);

        txtdst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtdst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesh", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia", " " }));
        jPanel1.add(txtdst);
        txtdst.setBounds(289, 221, 219, 40);
        jPanel1.add(txtdate);
        txtdate.setBounds(289, 288, 219, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(351, 554, 172, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\kkhhkkhh.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1330, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtflightActionPerformed

    private void txtdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeptActionPerformed

 
 
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        

String id = txtfid.getText();
String flightname = txtflight.getText();
String source = txtsrc.getSelectedItem().toString();
 
                     
String destination =txtdst.getSelectedItem().toString();
                    
//DateFormat da= new SimpleDateFormat("yyyy-MM-dd");
//String date= da.format(txtdate.getDate());
//see this;;
String date= txtdate.getText();

String deptime= txtdept.getText();
String arrivaltime= txtarr.getText();
String flicharge= txtfchrg.getText();





        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
              pst = con.prepareStatement("update flight set flightname=?,source=?,destination=?,date=?,arrivaltime=?,deptime=?,flicharge=? where id=?");
             
              pst.setString(1,flightname);
              pst.setString(2,source);
             
              pst.setString(3,destination);
              
              pst.setString(4,date);
              
              pst.setString(5,arrivaltime);
              
              pst.setString(6,deptime);
              
              pst.setString(7,flicharge);
              pst.setString(8,id);
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"Flight details updated Successfully!!!");
            
               txtfid.setText("");
              
              txtflight.setText("");
               
               txtsrc.setSelectedIndex(0);
               txtdst.setSelectedIndex(0);
               
               
               
               
               txtdate.setText("");
              txtdept.setText("");
              txtarr.setText("");
              txtfchrg.setText("");
              
             
       
              
       
        }
        
            
            
            
         catch (ClassNotFoundException ex) {
            Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
        }
              catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
         
 
    
    
    
    private void txtarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtarrActionPerformed

    private void txtfchrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfchrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfchrgActionPerformed

     public void autoID()
    {
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            java.sql.Statement s = con.createStatement();
             ResultSet rs = s.executeQuery("select MAX(id) from flight ");
             rs.next();
             rs.getString("MAX(id)");
             if(rs.getString("MAX(id)") == null)
             {
             txtfid.setText("FL001");
                 
             }
             
             else 
             {
               long id = Long.parseLong(rs.getString("MAX(id)").substring(2,rs.getString("MAX(id)").length()));
               id++;
               txtfid.setText("FL" + String.format("%03d", id));
             }
             
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   
   
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
        
        this.hide();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String id = txtfid.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
             pst = con.prepareStatement("select * from flight where id = ?");
             pst.setString(1,id);
            ResultSet rs = pst.executeQuery();
             if(rs.next() == false)
             {
                 JOptionPane.showMessageDialog(this,"Record Not Found!!!");
             }
             else
             {
                 String flightname=rs.getString("flightname");
                 String source =rs.getString("source");
                 
                  String destination =rs.getString("destination");
                 
                   String date =rs.getString("date");
                    String deptime =rs.getString("deptime");
                     String arrivaltime =rs.getString("arrivaltime");
                      String flicharge =rs.getString("flicharge");
                       
                      txtflight.setText(flightname.trim());
             
                  
          
                     txtsrc.setSelectedItem(source.trim());//wow!!!!!!!!!!!!!!!!!!!
        
        
        
                     
                     txtdst.setSelectedItem(destination.trim());
                        
                    
                      txtdate.setText(date.trim());
                      txtdept.setText(deptime.trim());
                      txtarr.setText(arrivaltime.trim());
                      txtfchrg.setText(flicharge.trim());
                     
                      
            
                
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
             }
             
             
             
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(searchflight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(searchflight.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String fid = txtfid.getText();
       
        try {
            // TODO add your handling code here:
            
            
            
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
             //String sql = "DELETE FROM flight where id=id";
             
             java.sql.Statement s = (java.sql.Statement)con.createStatement();
             
            
             s.executeUpdate("DELETE  FROM flight WHERE id='"+fid+"'");
             
             
              JOptionPane.showMessageDialog(null,"Flight details Deleted Successfully!!!");
               txtflight.setText("");
               
               txtsrc.setSelectedIndex(0);
               txtdst.setSelectedIndex(0);
               
               txtdate.setText("");
               
               
               txtdate.setText("");
              txtdept.setText("");
              txtarr.setText("");
              txtfchrg.setText("");
              autoID();
             

              
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(searchflight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(searchflight.class.getName()).log(Level.SEVERE, null, ex);
        }
             
            catch(Exception e) 
            {
        JOptionPane.showMessageDialog(this,e.getMessage());
        
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

  
   
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private datechooser.beans.DateChooserPanel dateChooserPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtarr;
    private datechooser.beans.DateChooserPanel txtdat;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdept;
    private javax.swing.JComboBox<String> txtdst;
    private javax.swing.JTextField txtfchrg;
    private javax.swing.JTextField txtfid;
    private javax.swing.JTextField txtflight;
    private javax.swing.JComboBox<String> txtsrc;
    // End of variables declaration//GEN-END:variables
}
