
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import javax.swing.JDesktopPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class tickets extends javax.swing.JInternalFrame {

    /**
     * Creates new form tickets
     */
    public tickets() {
        initComponents();
        autoID();
    }
    
    
    
    
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsrc = new javax.swing.JComboBox<>();
        txtdst = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttik = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtpassport = new javax.swing.JLabel();
        txtfid = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtflightname = new javax.swing.JLabel();
        txtdeptime = new javax.swing.JLabel();
        txtclass = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        txtseats = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        txtcid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txttotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        src = new javax.swing.JComboBox<>();
        dst = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txttid = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 0, 102));
        setPreferredSize(new java.awt.Dimension(1300, 1000));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECT COUNTRY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 1, 25), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);

        txtsrc.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        txtsrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesg", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia", " " }));
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        jPanel1.add(txtsrc);
        txtsrc.setBounds(262, 33, 205, 34);

        txtdst.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        txtdst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesg", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia", " " }));
        txtdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdstActionPerformed(evt);
            }
        });
        jPanel1.add(txtdst);
        txtdst.setBounds(262, 77, 205, 35);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 20)); // NOI18N
        jLabel1.setText("Source");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(39, 37, 162, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 3, 20)); // NOI18N
        jLabel2.setText("Destination");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(39, 77, 162, 42);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 255));
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(541, 55, 131, 42);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Fligjht Name", "Source", "Destination", "Date", "Departure Time", "Arrival Time", "Flight Charge"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Flight ID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Fligjht Name");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Source");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Destination");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Date");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Departure Time");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Arrival Time");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("flight Charge");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(9, 160, 679, 339);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("TICKET NUMBER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(27, 22, 222, 39);

        txttik.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txttik.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(txttik);
        txttik.setBounds(311, 22, 204, 39);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(883, 644));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Customer ID");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(31, 11, 144, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel6.setText("First Name");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(16, 57, 159, 33);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(16, 96, 149, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel8.setText("Passport ID");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(16, 132, 151, 36);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel9.setText("Flight ID");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(16, 188, 121, 31);

        txtfirstname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtfirstname);
        txtfirstname.setBounds(204, 57, 273, 31);

        txtlastname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtlastname);
        txtlastname.setBounds(204, 94, 273, 31);

        txtpassport.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtpassport.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtpassport);
        txtpassport.setBounds(204, 132, 273, 36);

        txtfid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txtfid.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtfid);
        txtfid.setBounds(204, 188, 273, 32);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel18.setText("Fair Of One seat");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(16, 339, 170, 31);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel10.setText("Flight Name");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(16, 225, 117, 29);

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel17.setText("Class");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(16, 305, 91, 28);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel16.setText("Departure Time");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(16, 260, 132, 36);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        jLabel19.setText("Number Of Seats");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(16, 376, 170, 28);

        txtflightname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtflightname.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtflightname);
        txtflightname.setBounds(204, 226, 273, 29);

        txtdeptime.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtdeptime.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtdeptime);
        txtdeptime.setBounds(204, 261, 273, 35);

        txtclass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Business", " " }));
        txtclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclassActionPerformed(evt);
            }
        });
        jPanel3.add(txtclass);
        txtclass.setBounds(204, 302, 177, 30);

        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtprice.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(txtprice);
        txtprice.setBounds(204, 339, 177, 31);

        txtseats.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtseats.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtseatsStateChanged(evt);
            }
        });
        jPanel3.add(txtseats);
        txtseats.setBounds(204, 376, 112, 25);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(405, 11, 160, 50);

        txtcid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidActionPerformed(evt);
            }
        });
        jPanel3.add(txtcid);
        txtcid.setBounds(204, 11, 146, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel12.setText("Date Of Journey");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(16, 410, 170, 34);

        txtdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txtdate);
        txtdate.setBounds(204, 414, 177, 34);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(700, 70, 660, 454);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("BOOK FLIGHT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 530, 219, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1070, 530, 149, 50);

        txttotal.setBackground(new java.awt.Color(255, 255, 51));
        txttotal.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        txttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttotalMouseClicked(evt);
            }
        });
        getContentPane().add(txttotal);
        txttotal.setBounds(400, 540, 210, 76);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText(" TOTAL PRICE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 540, 242, 76);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setText("=");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 540, 17, 76);

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText("  SELECT COUNTRY");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(131, 0, 296, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Source");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 51, 145, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Destination");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 102, 145, 40);

        src.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        src.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesh", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "Japan", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia" }));
        src.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcActionPerformed(evt);
            }
        });
        getContentPane().add(src);
        src.setBounds(197, 54, 230, 40);

        dst.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        dst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Algeria", "Argentina", "Armenia", "Australia", "Bahrain", "Bangladesh", "Belgium", "Bhutan", "Brazil", "china", "denmark", "Egypt", "France", "India ", "Iran", "Japan", "libya", "mauritius", "Oman", "Pakistan", "Qatar", "yemen", "Zambia" }));
        dst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstActionPerformed(evt);
            }
        });
        getContentPane().add(dst);
        dst.setBounds(197, 102, 230, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(463, 67, 160, 54);

        jLabel20.setBackground(new java.awt.Color(204, 204, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 0));
        jLabel20.setText("TICKET NUMBER");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(720, 0, 260, 40);

        txttid.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        txttid.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(txttid);
        txttid.setBounds(1020, 0, 202, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 204));
        jLabel21.setText("    BOOK FLIGHT");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(900, 40, 332, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void txtdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdstActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

   
    
    

    
    
    private void txtclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclassActionPerformed

    
    
 
    
    
    
     
    
    
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:jjgjhgjhgjgjhgjh
        
         String ticketid = txttid.getText();
         String flightid = txtfid.getText();
         String custid = txtcid.getText();
         String flightclass = txtclass.getSelectedItem().toString().trim();
         String price = txtprice.getText();
         String seats = txtseats.getValue().toString();     //must initialize
         
          String date = txtdate.getText();
         
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            
            pst = con.prepareStatement("insert into tickets(id,flid,custid,class,price,seats,date)values(?,?,?,?,?,?,?)");
             
            
             pst.setString(1,ticketid);
             
            
              pst.setString(2,flightid);
              
              pst.setString(3,custid);
             
              pst.setString(4,flightclass);
              
              pst.setString(5,price);
              
              pst.setString(6,seats);
              
              pst.setString(7,date);
              
             
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"Ticket Booked Successfully!!!");
              JOptionPane.showMessageDialog(null,"DO you want to proceed Payment!!!");
              payment p = new payment();
        JDesktopPane dp =getDesktopPane();    //very nice!!! Happy
         dp.add(p);
       p.show();
       txtcid.setText("");
               txtfirstname.setText("");
            txtlastname.setText("");
                txtpassport.setText("");
               txtflightname.setText("");
                      txtfid.setText("");
               txtdeptime.setText("");
               txtclass.setSelectedItem(0);
              txtprice.setText("");
              txtdate.setText("");
              txttotal.setText("");
              
              
              autoID();
             
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
             
              
         
         
         
           
                       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
         String id = txtcid.getText();
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            
            
            
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
             pst = con.prepareStatement("Select * from customer where id=?");
             pst.setString(1,id);
             ResultSet rs = pst.executeQuery();
              if(rs.next()==false)
              {
                  JOptionPane.showMessageDialog(this,"Record not found!!!");
                  
              }
             
             else
              {
                  String fname=rs.getString("firstname");
                    String lname=rs.getString("lastname");
                      String passport=rs.getString("passport");
                           
                              
                              txtfirstname.setText(fname.trim());
                              
                                txtlastname.setText(lname.trim());
  txtpassport.setText(passport.trim());
          }
             
        
        
            
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
   public void autoID()
    {
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            java.sql.Statement s = con.createStatement();
             ResultSet rs = s.executeQuery("select MAX(id) from tickets ");
             rs.next();
             rs.getString("MAX(id)");
             if(rs.getString("MAX(id)") == null)
             {
              txttid.setText("TK001");
                 
             }
             
             else 
             {
               long id = Long.parseLong(rs.getString("MAX(id)").substring(2,rs.getString("MAX(id)").length()));
               id++;
               txttid.setText("TK" + String.format("%03d", id));
             }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   

    
    
    
    
    private void txtcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidActionPerformed

    private void txtseatsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtseatsStateChanged
        // TODO add your handling code here:
        
        int price = Integer.parseInt(txtprice.getText());
        int qty= Integer.parseInt(txtseats.getValue().toString());
        int total = price * qty;
        txttotal.setText(String.valueOf(total));
        
        
        
    }//GEN-LAST:event_txtseatsStateChanged

    private void txttotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotalMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txttotalMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();

        int selectIndex = jTable1.getSelectedRow();

        txtfid.setText(Df.getValueAt(selectIndex, 0).toString());
        txtflightname.setText(Df.getValueAt(selectIndex, 1).toString());
        txtdeptime.setText(Df.getValueAt(selectIndex, 5).toString());
        txtprice.setText(Df.getValueAt(selectIndex, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void srcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcActionPerformed

    private void dstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        String source = src.getSelectedItem().toString();
        String destination = dst.getSelectedItem().toString();
        
        
        
        
            
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            pst = con.prepareStatement("select * from flight where source = ? and destination = ?");
            pst.setString(1, source);
            pst.setString(2, destination);
            ResultSet rs = pst.executeQuery();
         
             
              
            ResultSetMetaData rsm = rs.getMetaData();
            int c;
            c = rsm.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            
            
           
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1;i<=c;i++)
                {
                    v2.add(rs.getString("id"));   //check!!!!!
                    v2.add(rs.getString("flightname"));   
                    v2.add(rs.getString("source"));   
                    v2.add(rs.getString("destination"));   
                    v2.add(rs.getString("date"));   
                    v2.add(rs.getString("deptime"));   
                    v2.add(rs.getString("arrivaltime"));   
                    v2.add(rs.getString("flicharge"));   
                    
                    
                }
                Df.addRow(v2);
               txtsrc.setSelectedIndex(-1);
              txtdst.setSelectedIndex(-1); 
              
         
             
                  JOptionPane.showMessageDialog(this,"Record found!!!");
             
            
            
        
           
            
            
            }    
            
        }
        
        
        
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

  
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> src;
    private javax.swing.JTextField txtcid;
    private javax.swing.JComboBox<String> txtclass;
    private javax.swing.JTextField txtdate;
    private javax.swing.JLabel txtdeptime;
    private javax.swing.JComboBox<String> txtdst;
    private javax.swing.JLabel txtfid;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtflightname;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtpassport;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtseats;
    private javax.swing.JComboBox<String> txtsrc;
    private javax.swing.JLabel txttid;
    private javax.swing.JLabel txttik;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
