
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.regex.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class usercreation extends javax.swing.JInternalFrame {

    /**
     * Creates new form usercreation
     */
    public usercreation() {
        initComponents();
        Connect();
        Load_user();
         autoID();
        
    }

    
    
       Connection con;
       PreparedStatement pst;
       DefaultTableModel Df;
       

       
       public void Connect()
       {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(usercreation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(usercreation.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
       }
       
       
       public void Load_user()
       {
           int c;
           
        try {
            pst = con.prepareStatement("select * from user");
            ResultSet rs = pst.executeQuery();
             DefaultTableModel Df;
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            
            Df= (DefaultTableModel)jtble.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2 =new Vector();
                for(int i=1;i<=c;i++)
                {
                    v2.add(rs.getString("id"));   //check!!!!!
                    v2.add(rs.getString("firstname"));   
                    v2.add(rs.getString("lastname"));   
                    v2.add(rs.getString("email"));   
                    v2.add(rs.getString("usertype"));   

                       
                }
                Df.addRow(v2);
            }
                    }
        catch (SQLException ex) {
            Logger.getLogger(usercreation.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
           }
              

       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtfn = new javax.swing.JTextField();
        txtln = new javax.swing.JTextField();
        txtun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpasswd = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtble = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtuid = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        eml = new javax.swing.JTextField();
        pas = new javax.swing.JPasswordField();
        elab = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1336, 768));
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 0, 102), new java.awt.Color(204, 204, 255)));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(142, 326, 0, 0);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setText("User ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 23, 108, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 81, 106, 35);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(24, 146, 112, 35);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setText("Email Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 211, 170, 35);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(24, 288, 105, 36);

        txtid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 0, 51));
        txtid.setText("jLabel7");
        jPanel1.add(txtid);
        txtid.setBounds(241, 14, 211, 37);

        txtfn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtfn);
        txtfn.setBounds(232, 81, 307, 35);

        txtln.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnActionPerformed(evt);
            }
        });
        jPanel1.add(txtln);
        txtln.setBounds(232, 148, 307, 35);

        txtun.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunActionPerformed(evt);
            }
        });
        txtun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunKeyReleased(evt);
            }
        });
        jPanel1.add(txtun);
        txtun.setBounds(232, 213, 307, 35);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(24, 353, 149, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 51));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(377, 353, 154, 50);

        txtpasswd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txtpasswd);
        txtpasswd.setBounds(232, 290, 307, 36);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 51));
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(213, 353, 140, 50);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 0, 51));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(24, 433, 149, 54);

        email.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(email);
        email.setBounds(232, 251, 307, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(18, 93, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(204, 204, 255)));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel8.setText("User ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(45, 114, 209, 37);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel9.setText("First Name");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(45, 171, 209, 31);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel10.setText("Last Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(45, 232, 209, 34);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel11.setText("Email Address");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(45, 302, 209, 32);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel12.setText("Password");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(44, 374, 210, 34);

        jtble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USER ID", "First Name", "Last Name", "Email Address", "User Type"
            }
        ));
        jtble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtble);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(610, 420, 680, 200);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("USER CREATION");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 20, 330, 48);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(30, 500, 150, 40);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton6.setText("EDIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(220, 500, 130, 40);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(400, 500, 160, 40);

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton8.setText("CANCEL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(30, 560, 160, 40);

        txtuid.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        txtuid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(txtuid);
        txtuid.setBounds(272, 114, 269, 37);

        fn.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        jPanel2.add(fn);
        fn.setBounds(272, 169, 269, 33);

        ln.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });
        jPanel2.add(ln);
        ln.setBounds(272, 232, 269, 34);

        eml.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        eml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emlActionPerformed(evt);
            }
        });
        eml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emlKeyReleased(evt);
            }
        });
        jPanel2.add(eml);
        eml.setBounds(272, 302, 269, 32);

        pas.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });
        pas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pasKeyReleased(evt);
            }
        });
        jPanel2.add(pas);
        pas.setBounds(272, 374, 269, 34);

        elab.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        elab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(elab);
        elab.setBounds(251, 340, 350, 28);

        f.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        f.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(f);
        f.setBounds(250, 200, 350, 30);

        l.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        l.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(l);
        l.setBounds(240, 270, 360, 30);

        p.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        p.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(p);
        p.setBounds(10, 410, 610, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        jLabel13.setText("User Type");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 440, 140, 40);

        txtus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Passenger", "Receptionalist" }));
        txtus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusActionPerformed(evt);
            }
        });
        jPanel2.add(txtus);
        txtus.setBounds(270, 440, 240, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon("F:\\111111111111111111111111111111111111111.jpg")); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 4, 1330, 740);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1330, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnActionPerformed

    private void txtunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunActionPerformed

    
   
    
    
    
    public void autoID()
    {
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
            java.sql.Statement s = con.createStatement();
             ResultSet rs = s.executeQuery("select MAX(id) from user ");
             rs.next();
             rs.getString("MAX(id)");
             if(rs.getString("MAX(id)") == null)
             {
              txtuid.setText("UC001");
                 
             }
             
             else 
             {
               long id = Long.parseLong(rs.getString("MAX(id)").substring(2,rs.getString("MAX(id)").length()));
               id++;
               txtuid.setText("UC" + String.format("%03d", id));
             }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
       
       
       
       
       
       
       
       
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbleMouseClicked
        // TODO add your handling code here:
        
        Df = (DefaultTableModel)jtble.getModel();
        
        int selectIndex =jtble.getSelectedRow();
        txtuid.setText(Df.getValueAt(selectIndex,0).toString());
         fn.setText(Df.getValueAt(selectIndex,1).toString());
          ln.setText(Df.getValueAt(selectIndex,2).toString());
           eml.setText(Df.getValueAt(selectIndex,3).toString());
          txtus.setSelectedItem(Df.getValueAt(selectIndex,4).toString());
             jButton5.setEnabled(false);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jtbleMouseClicked

    private void txtunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtunKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        String id = txtuid.getText();
String firstname = fn.getText();
String lastname = ln.getText();
String emailid = eml.getText();
String password = pas.getText();
String usertype = txtus.getSelectedItem().toString();


if(firstname.equals(""))
     {
         JOptionPane.showMessageDialog(null,"First Name is Mandatory!!");
     
     }
     
     else if(lastname.equals(""))
     {
         JOptionPane.showMessageDialog(null,"Last Name ID Is Mandatory!!");
     }

     
     else if(emailid.equals(""))
     {
         JOptionPane.showMessageDialog(null,"Email Is Mandatory!!");
     }

     else if(password.equals(""))
     {
         JOptionPane.showMessageDialog(null,"Password Is Mandatory!!");
     }
     
      else
         {
         JOptionPane.showMessageDialog(null,"Validation Success!!");
     }

















        try {
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
              pst = con.prepareStatement("insert into user(id,firstname,lastname,email,password,usertype)values(?,?,?,?,?,?)");
              pst.setString(1,id);
              pst.setString(2,firstname);
              pst.setString(3,lastname);
             
              pst.setString(4,emailid);
              
              pst.setString(5,password);
               pst.setString(6,usertype);

              
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"User Created Successfully!!!");
              
              
              
              fn.setText("");
               ln.setText("");
               eml.setText("");
              pas.setText("");
              txtus.setSelectedIndex(0);
              fn.requestFocus();
              autoID();
              
              Load_user();
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
                
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         String id = txtuid.getText();
String firstname = fn.getText();
String lastname = ln.getText();
String emailid = eml.getText();
String usertype = txtus.getSelectedItem().toString();





        try {
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
              pst = con.prepareStatement("update user set firstname=?,lastname=?,email=?,usertype=? where id=?");
              
              pst.setString(1,firstname);
              pst.setString(2,lastname);
             
              pst.setString(3,emailid);
              pst.setString(4,usertype);

              pst.setString(5,id);
             // pst.setString(5,password);
              
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"User Edited Successfully!!!");
              
              
              
              fn.setText("");
               ln.setText("");
               eml.setText("");
              pas.setText("");
                txtus.setSelectedIndex(0);
              autoID();
            fn.requestFocus();

              Load_user();
               jButton5.setEnabled(true);
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                this.hide();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void emlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emlKeyReleased
        // TODO add your handling code here:
         String PATTERN ="^[a-zA-Z0-9]{0,30}@[a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(eml.getText());
        if(!match.matches())
        {
            elab.setText("Email Is Invalid!!");
            
        }
        else 
        {
                        elab.setText(null);

        }
        
        
    }//GEN-LAST:event_emlKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        
         String id = txtuid.getText();
  
       
       
         try {
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Airlines","root","safahmi7.");
              pst = con.prepareStatement("delete from user where id=?");
              
            
              pst.setString(1,id);
             
              
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"User Deleted Successfully!!!");
              
              
              
              fn.setText("");
               ln.setText("");
               eml.setText("");
              pas.setText("");
              txtus.setSelectedIndex(0);
              
              autoID();
              
              Load_user();
               jButton5.setEnabled(true);
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void emlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emlActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
        // TODO add your handling code he
        
        String PATTERN ="^[A-Za-z]{0,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(fn.getText());
        if(!match.matches())
        {
            f.setText("Naming Is Incorrect! use only alphabets!!");
            
        }
        else 
        {
                        f.setText(null);

        }
        
        
        
        
        
    }//GEN-LAST:event_fnKeyReleased

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
        // TODO add your handling code here:
        
        
        String PATTERN ="^[A-Za-z]{0,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(ln.getText());
        if(!match.matches())
        {
            l.setText("Naming Is Incorrect!use only alphabets !!");
            
        }
        else 
        {
                        l.setText(null);

        }
        
        
        
        
    }//GEN-LAST:event_lnKeyReleased

    private void pasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasKeyReleased
        // TODO add your handling code here:
        
        
        String PATTERN ="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,256}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(pas.getText());
        if(!match.matches())
        {
            p.setText("Password must contain atleast one DIGIT,one LOWER CASE ,one UPPER CASE letter & a character!!");
            
        }
        else 
        {
                        p.setText(null);

        }
        
        
        
    }//GEN-LAST:event_pasKeyReleased

    private void txtusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elab;
    private javax.swing.JLabel email;
    private javax.swing.JTextField eml;
    private javax.swing.JLabel f;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtble;
    private javax.swing.JLabel l;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel p;
    private javax.swing.JPasswordField pas;
    private javax.swing.JTextField txtfn;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtln;
    private javax.swing.JPasswordField txtpasswd;
    private javax.swing.JLabel txtuid;
    private javax.swing.JTextField txtun;
    private javax.swing.JComboBox<String> txtus;
    // End of variables declaration//GEN-END:variables
}
